[package]
name = "rocket-nepenthes"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
log = "0.4.27"
markovish = "0.2.2"
rand = "0.9.1"
rocket = "0.5.1"
rust-embed = "8.7.2"
urlencoding = "2.1.3"
